sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
cache: pip
matrix:
  fast_finish: true
  include:
  - name: "Minimum Nextflow version, regular test suite"
    env: NXF_VER='0.32.0' SUITE=test FLAGS=
    language: java
    jdk: openjdk8
  - name: "Latest Nextflow version, regular test suite"
    env: NXF_VER='' SUITE=test FLAGS=
  - name: "Latest Nextflow version, regular test suite with splitKmers, ensure that `protein` can't be specified"
    # Check exit code to make sure it is nonzero for --splitKmer + --molecules protein
    script:
      - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker --splitKmer ; if [ $? -eq 0 ]; then echo "--splitKmer + --molecules protein should fail but did not" && exit 1 ; else echo "Correctly failed --splitKmer + --molecules protein" ; fi
  - name: "Latest Nextflow version, split k-mer test suite"
    env: NXF_VER='' SUITE=test_ska FLAGS=
  - name: "Latest Nextflow version, split k-mer test suite, test subsampling"
    env: NXF_VER='' SUITE=test_ska FLAGS=--subsample 10
  - name: "Lint the pipeline code"
    install:
      # Install nf-core/tools
      - pip install --upgrade pip
      - pip install nf-core
    script: nf-core lint ${TRAVIS_BUILD_DIR}
    python: '3.6'
    jdk: openjdk8
  # - name: "Lint the documentation"
  #   script: markdownlint ${TRAVIS_BUILD_DIR} -c ${TRAVIS_BUILD_DIR}/.github/markdownlint.yml
  - name: "Test nextflow kmermaid, with 10x .tgz file"
    env: NXF_VER='' SUITE=test_tenx_tgz FLAGS=
  - name: "Test nextflow kmermaid, with 10x .tgz file"
    env: NXF_VER='' SUITE=test_tenx_tgz FLAGS=--skip_trimming

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && ([ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ] || [ $TRAVIS_PULL_REQUEST_BRANCH = "patch" ]))'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull nfcore/kmermaid:dev
  # Fake the tag locally so that the pipeline runs properly
  - docker tag nfcore/kmermaid:dev nfcore/kmermaid:dev

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli

script:
  # Run the pipeline with the test profile
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker ${FLAGS}
