# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-kmermaid-1.0.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::khmer=3.0.0a3
  - bioconda::bioconductor-edger=3.28.0
  - conda-forge::gxx_linux-64=7.3.0
  - conda-forge::rust=1.40.0
  - conda-forge::r-data.table=1.12.4
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=1.1
  - alabaster=0.7.12
  - fastp=0.20.0
  - fastqc=0.11.9
  - matplotlib=3.1.1 # don't upgrade, multiqc conflict
  - multiqc=1.8
  - numpy=1.17.5
  - pathos=0.2.5
  - pip=20.0.2
  - pysam=0.15.4
  - pytest=5.3.4
  - seqtk=1.3
  - ska=1.0
  - sphinx=2.3.1
  - pip:
    - git+https://github.com/czbiohub/kh-tools.git@master#egg=khtools==0.1.0
    - git+https://github.com/czbiohub/sourmash.git@master#egg=sourmash==3.2.0
